Article harmonisation
Wilsven/healthhub-content-optimization pull request #100
Opened 2024-07-15 06:30 UTC by jinchad

![photo_2024-07-15_14-30-13](https://github.com/user-attachments/assets/c515904c-3e42-4580-a7e4-9ec5342e36c1)
Ran through lint and files passed.

2024-07-15 06:57 UTC, Wilsven commented
Please check the GitHub Actions to debug the issue. I believe `ruff` does not check `.ipynb` notebooks.

2024-07-15 06:58 UTC, Wilsven commented
> Please check the GitHub Actions to debug the issue. I believe `ruff` does not check `.ipynb` notebooks.

It seems like you have successfully debugged the issue. Feel free to ignore this comment.

2024-07-15 11:35 UTC, Wilsven commented on .gitignore
> +.env
Did you check if the `.gitignore` already contains this? I'm pretty sure it does so please check and modify if necessary.

2024-07-15 11:37 UTC, Wilsven commented on .gitignore
> +hh_venv/
It's standard practice to name your virtual environment `venv` which would have already been taken care of by the `.gitignore`. So please modify this. Thanks.

2024-07-15 11:42 UTC, Wilsven commented on article-harmonisation/requirements.txt
Are you sure your project requires this many packages?

2024-07-15 11:44 UTC, Wilsven commented on article-harmonisation/README.md
`README.md` seems incomplete. You have provided instructions on how to get the `HUGGINGFACEHUB_API_TOKEN` but what about the `LANGCHAIN_API_KEY`? Please also make sure your instructions in the `README.md` is as clear as possible.

2024-07-15 11:44 UTC, Wilsven requested changes
I have left some comments for review. Please resolve before making another PR. @jinchad

2024-07-16 06:50 UTC, jinchad commented on .gitignore
> +.env
removed

2024-07-16 06:51 UTC, jinchad commented on .gitignore
> +hh_venv/
deleted `hh_venv` and created a new venv called `venv`

2024-07-16 06:51 UTC, jinchad commented on article-harmonisation/requirements.txt
new requirements.txt will have lesser packages

2024-07-16 06:52 UTC, jinchad commented on article-harmonisation/README.md
`LANGCHAIN_API_KEY` no longer needed, hence removed.

2024-07-16 06:59 UTC, Wilsven commented on article-harmonisation/requirements.txt
Care to elaborate?

2024-07-16 07:04 UTC, jinchad commented on article-harmonisation/requirements.txt
Sure, i have created a new venv, and installed the packages one by one again while ensuring that the files can still run smoothly. I got a requirements.txt at the end with lesser packages.

2024-07-16 07:04 UTC, Wilsven commented
@jinchad Please resolve the merge conflicts and have proper description of your PR. For now, I am unclear what this PR is about. From what I know about what you've commented in Trello, it seems you're trying to share the prompt templates you've used? It is currently unclear. Please fix and re-request review at the top right corner. Or please close this PR and make a new one. Thanks.

2024-07-16 07:07 UTC, Wilsven commented on article-harmonisation/requirements.txt
Thanks, I will resolve this conversation then.

2024-07-16 07:10 UTC, jinchad commented
@Wilsven This PR was done as per your instructions under the Trello card "Create Slides on GenAI Development" which is under Project Management now.

2024-07-16 07:14 UTC, Wilsven commented
> @Wilsven This PR was done as per your instructions under the Trello card "Create Slides on GenAI Development" which is under Project Management now.

<img width="1312" alt="image" src="https://github.com/user-attachments/assets/13250157-af78-4210-86e5-4e55776894b6">

Your description on your PR should go here. Please click into the tab "Files changed" and give proper description about each of the changes you're committing to this PR. It is currently unclear. 

**Note:** Do resolve the merge conflict of the `CHANGELOG.md` as well. Thanks. Please take note not to overwrite anyone's changes. Check before you confirm something permanent.

2024-07-16 07:19 UTC, Wilsven requested changes

2024-07-16 07:19 UTC, Wilsven commented on CHANGELOG.md
There's a merge conflict for this file. Please make the necessary amends.

2024-07-16 07:19 UTC, Wilsven commented on pyvenv.cfg
Is this meant to be committed into Version Control?

2024-07-16 08:02 UTC, issacj-17 commented on CHANGELOG.md
Yeap, I will do this. There was a bug when I was checking out my branch and merging some changes to kedro-text-preprocess.

2024-07-16 08:15 UTC, Wilsven commented
> PR request to share prompts as instructed by @Wilsven on Trello card "Create Slides on GenAI Development" under Project Management

@jinchad Just to let you descriptions for your PR are meant to be informative. This is bad practice if you're going to type something arbitrary. But if you're going to do it nonetheless, please at least add the link to the Trello card. 

You may consult @issacj-17 on how he provides informative descriptions to his PRs. I believe he does it pretty well so it would be a good learning opportunity for you. Thanks all!

2024-07-16 09:43 UTC, Wilsven approved these changes

2024-07-16 09:47 UTC, Wilsven commented
@jinchad @issacj-17 Before we merge this PR into `main`, is there a documentation somewhere on how these can be run? Or is that still in the works?

2024-07-16 09:57 UTC, jinchad commented
@Wilsven I have updated the description in this PR and took advice from @issacj-17. Will have more informative descriptions in future PR from now on. To answer your question on the documentation on how to run the project: the project can be run after installing the packages in `requirements.txt` and running `harmonisation.py`

2024-07-16 10:00 UTC, Wilsven commented
> @Wilsven I have updated the description in this PR and took advice from @issacj-17. Will have more informative descriptions in future PR from now on. To answer your question on the documentation on how to run the project: the project can be run after installing the packages in `requirements.txt` and running `harmonisation.py`. I will add that into the `README.md`

Nice job, it is very well done @jinchad . Also, thanks @issacj-17. 

Once the `README.md` has been updated on how to run the `harmonisation.py` file, I will merge the PR.

2024-07-16 10:04 UTC, jinchad commented
@Wilsven The README has been updated with instructions on how to run the project. Thank you.

2024-07-16 10:33 UTC, Wilsven commented
Give me some time. Will review and merge if there are no more changes to be made. Thank you.

2024-07-16 11:12 UTC, merged