Added the content body of selected articles with `Excel Errors` back into the dataset
Wilsven/healthhub-content-optimization pull request #101
Opened 2024-07-15 14:31 UTC by issacj-17

## Update evaluate_text_extraction.ipynb
- Cleaned up the notebook to evaluate text extraction

## Added kedro node to add Raw HTML back to dataset
- Added 2 file pointers in catalog.yml to `missing_content` to add back selected files with Excel Errors
- Created `add_content` node to add txt files corresponding to Excel Errors back to dataset
- Implement statement to change remove_type to `Multilingual` for content body whose language is not in English
- Change `to_remove` to False and `remove_type` to None for the remaining articles
- Amended pipeline and downstream nodes with update parameters

## Create .gitkeep
- Create .gitkeep for missing_content (Refer to https://trello.com/c/n0cMa6k2/68-raw-data for access to data)

## Update README.md
- Added additional directory that points to articles with `Excel Errors` that are designated as `keep`

2024-07-15 14:59 UTC, issacj-17 commented
@jzkoh @jwyting @Wilsven @sixiannn The pipeline has been amended to include the selected article with Excel Errors. Please rerun the pipeline once the branch has been merged into `main`

2024-07-15 15:01 UTC, Wilsven commented
> @jzkoh @jwyting @Wilsven @sixiannn The pipeline has been amended to include the selected article with Excel Errors. Please rerun the pipeline once the branch has been merged into `main`

Have you ran the tests? It's not documented yet but I have mentioned you in the respective PRs when I added this feature. Do refer to those for now.

2024-07-15 16:31 UTC, Wilsven commented
![](https://github.trello.services/images/mini-trello-icon.png) [Review excel provided by JingYi](https://trello.com/c/w9a1kB4x/146-review-excel-provided-by-jingyi)

2024-07-16 00:38 UTC, issacj-17 commented
> > @jzkoh @jwyting @Wilsven @sixiannn The pipeline has been amended to include the selected article with Excel Errors. Please rerun the pipeline once the branch has been merged into `main`
> 
> Have you ran the tests? It's not documented yet but I have mentioned you in the respective PRs when I added this feature. Do refer to those for now.

@Wilsven Yeap, I have just run the tests. A few bugs here and there. Some prevented the `pytest` package from even running. I have rectified them. I will be working on implementing some test cases for the new node.

2024-07-16 02:05 UTC, Wilsven commented
> @Wilsven Yeap, I have just run the tests. A few bugs here and there. Some prevented the `pytest` package from even running. I have rectified them. I will be working on implementing some test cases for the new node.

So are you done implementing the test cases for the new node or in the process of implementing? You need to generate some test data to run the tests. I haven't implemented that yet to populate some mock data. I have mentioned this in #94. Hope you have referred to it. Do keep me updated on this as we should expect to get this wrapped up today. Thanks!

2024-07-16 05:52 UTC, Wilsven commented
@issacj-17 I have made my change into `main` (#103) so you'd encounter some minor merge conflicts. Nothing major. Just keep the latest change with the `whitelist` argument. Thanks!

2024-07-16 07:57 UTC, issacj-17 commented
@Wilsven I have made the changes to the test cases and merged `main` into this branch. All test cases have passed. The branch is ready to be merged.

2024-07-16 08:39 UTC, Wilsven requested changes

2024-07-16 08:39 UTC, Wilsven commented on content-optimization/src/__init__.py
Please remove this folder. You can simply run `pip install -e .` to install the Kedro project as a package. After this, you're then able to simply import the function for your unit and integration tests like how you'd do imports for any other packages.

2024-07-16 08:39 UTC, Wilsven commented on content-optimization/src/content_optimization/pipelines/data_processing/nodes.py
Please revert these changes back.

2024-07-16 08:39 UTC, Wilsven commented on content-optimization/src/content_optimization/pipelines/data_processing/pipeline.py
Please revert these changes back.

2024-07-16 08:39 UTC, Wilsven commented on content-optimization/src/content_optimization/pipelines/feature_engineering/pipeline.py
Please revert these changes back.

2024-07-16 08:42 UTC, issacj-17 commented on content-optimization/src/content_optimization/pipelines/data_processing/nodes.py
Which one? If it is the imports, that is how you import the files in kedro project. The add_contents is to whitelist the excel error files

2024-07-16 08:43 UTC, issacj-17 commented on content-optimization/src/content_optimization/pipelines/data_processing/pipeline.py
Which one? If it is the imports, that is how you import the files in kedro project. The add_contents node is to whitelist the Excel error files

2024-07-16 08:44 UTC, Wilsven requested changes

2024-07-16 08:44 UTC, Wilsven commented on content-optimization/notebooks/presentation.ipynb
Did you accidentally cleared all outputs for the notebook?

2024-07-16 08:44 UTC, Wilsven commented on content-optimization/src/content_optimization/pipelines/data_processing/nodes.py
There is no need to change `from content_optimization.pipelines.data_processing.extractor import HTMLExtractor` to `from .extractor import HTMLExtractor`.

2024-07-16 08:45 UTC, Wilsven commented on content-optimization/src/content_optimization/pipelines/data_processing/pipeline.py
There is no need to change from `content_optimization.pipelines.data_processing.extractor import HTMLExtractor` to `from .extractor import HTMLExtractor`.

2024-07-16 08:45 UTC, Wilsven commented on content-optimization/src/content_optimization/pipelines/data_processing/nodes.py
There is no need to change from `content_optimization.pipelines.data_processing.extractor` import HTMLExtractor to `from .extractor import HTMLExtractor`.

2024-07-16 08:46 UTC, Wilsven commented on content-optimization/src/content_optimization/pipelines/data_processing/pipeline.py
There isn't a need to modify the imports.

2024-07-16 08:47 UTC, issacj-17 commented on content-optimization/src/content_optimization/pipelines/data_processing/nodes.py
There is. I cant run pytest because it says it cannot find src module or content-optimization

2024-07-16 08:47 UTC, issacj-17 commented on content-optimization/src/content_optimization/pipelines/data_processing/nodes.py
![Uploading Screenshot 2024-07-16 at 4.47.20 PM.png…]()

2024-07-16 08:54 UTC, issacj-17 commented on content-optimization/src/content_optimization/pipelines/data_processing/pipeline.py
[S](https://github.com/Wilsven/healthhub-content-optimization/pull/101#discussion_r1679006108)

2024-07-16 08:54 UTC, Wilsven commented on content-optimization/src/content_optimization/pipelines/data_processing/nodes.py
You couldn't run the pytest because you didn't do `pip install -e .` which installs the Kedro project as a package. If you did, you'd be able to import the functions in the tests directory without issue. 

> Pytest relies on relative imports to understand the file structure

It does not if you did `pip install -e .`. It's my bad I didn't mention so please do that and revert the changes to the import.

2024-07-16 08:55 UTC, Wilsven commented on content-optimization/notebooks/presentation.ipynb
Instead of clearing the notebook, you should debug it. It is also weird that your pre-commit passes when you cleared the notebook. The pre-commit shouldn't work on outputs in `.ipynb` files. Only on the code. Please amend.

2024-07-16 09:00 UTC, Wilsven commented on content-optimization/src/content_optimization/pipelines/data_processing/nodes.py
> https://docs.kedro.org/en/stable/tutorial/test_a_project.html#:~:text=from%20.nodes%20import%20evaluate_model%2C%20split_data%2C%20train_model
> 
> This is also how the example provides in testing as well

Get that this is shown in the example which also isn't wrong but there isn't a need for us to change in our case. Especially so when we have been writing the imports in that way since day 1. Furthermore, there's functionally nothing wrong with the imports in the first place. Like I have previously mentioned, you have to be precise in the things you want to make changes to. Do not change things if there are no improvements in functionality or QoL.

2024-07-16 09:01 UTC, Wilsven commented on content-optimization/src/content_optimization/pipelines/data_processing/pipeline.py
See replies [here](https://github.com/Wilsven/healthhub-content-optimization/pull/101#discussion_r1679006108).

2024-07-16 09:11 UTC, Wilsven commented on content-optimization/notebooks/presentation.ipynb
If this issue persists, let us discuss because it is interesting it is failing. If you recall, you did make a merge from `main`, right? So the fact that you were able to merge from `main` meant that this passed all checks to be able to exist in `main` in the first place.

2024-07-16 09:12 UTC, issacj-17 commented on content-optimization/src/content_optimization/pipelines/data_processing/nodes.py
Yeah, I know. Prior to knowing that pip install -e . was required. I could not execute the command `pytest` in the `content-optimization` folder. Also, when I tried to do so yesterday before several merges from main. There was a requirements conflict with spacy transformer which prevented me from installing the kedro project.

2024-07-16 09:14 UTC, issacj-17 commented on content-optimization/notebooks/presentation.ipynb
For mine, it will flag notebooks that are larger than 500kb. As I had previously installed it as a git hook, it will not let me push my changes. The same goes if my function exceeds 50 statements, requiring me to refactor it and decouple it into smaller functions

2024-07-16 09:15 UTC, Wilsven commented on content-optimization/src/content_optimization/pipelines/data_processing/nodes.py
In future, it is best practice to inform me on this error before making your own changes so it "works" on your local. GitHub is for collaboration. So if it doesn't work for you, it is best to consult if it worked for others. I am suspecting this may be due to some other irrelevant reason. 

Alternatively, you may raise an issue on GitHub and document it nicely with the hopes that others may benefit from should they encounter the same issue as you did.

2024-07-16 09:16 UTC, Wilsven commented on content-optimization/notebooks/presentation.ipynb
Why are you receiving such an error? What git hook did you install? Is this an issue you're facing locally or what?

2024-07-16 09:19 UTC, Wilsven commented on content-optimization/notebooks/presentation.ipynb
What is currently puzzling me is that I own the `presentation.ipynb` notebook and linted my code without issue before making a PR here (#103). So I am confused why you're facing some errors.

2024-07-16 09:31 UTC, issacj-17 commented on content-optimization/notebooks/presentation.ipynb
Alright, I have added back the presentation.ipynb file after downloading it from main.

2024-07-16 09:36 UTC, Wilsven commented on content-optimization/notebooks/presentation.ipynb
So what was the issue?

2024-07-16 10:35 UTC, issacj-17 commented on content-optimization/notebooks/presentation.ipynb
I deleted my .git/hooks

2024-07-16 10:42 UTC, Wilsven commented on content-optimization/notebooks/presentation.ipynb
Great, there you go. It's more of a local issue than a global one. I will resolve this now. Thank you for your hard work!

2024-07-16 11:09 UTC, Wilsven requested changes

2024-07-16 11:09 UTC, Wilsven commented on content-optimization/tests/pipelines/data_processing/test_nodes.py
> -        # Check if number of articles with extracted content body matches the number of text files
Good catch on this change! Just one minor thing, this test case will either always pass or always fail depending on the nature of your mock data. As long as your mock data does not contain an empty string for the `extracted_content_body`, this assertion will always pass. I am assuming yours always failed because of how you created your mock data. Nonetheless, this is a redundant assertion. Good catch!

2024-07-17 02:54 UTC, Wilsven commented
Are there any more changes for this PR? If not, resolve all reviews and re-request review at the top right. Thanks!

2024-07-17 04:02 UTC, issacj-17 reviewed
All changes have been completed. Function to flag multilingual content has also been implemented

2024-07-17 04:15 UTC, Wilsven requested changes

2024-07-17 04:15 UTC, Wilsven commented on content-optimization/src/content_optimization/pipelines/data_processing/utils.py
> +def flag_multilingual_content(df: pd.DataFrame) -> pd.DataFrame:
You need to make slight adjustments to this function. Please consult the other functions in `flag_articles_to_remove_after_extraction` to integrate the whitelist argument in case there's a need to whitelist articles in future.

2024-07-17 04:15 UTC, Wilsven commented on content-optimization/src/content_optimization/pipelines/data_processing/utils.py
> +    df = flag_multilingual_content(df)
Could you reorder `flag_multilingual_content` to before `flag_below_word_count_cutoff`? Would this break anything?

We should maintain the order in which we perform the flagging. `Below Word Count` is something more arbitrary so if it exists as the last flag, it will reduce the number of articles required for review (do recall that articles below a certain word count threshold may not necessarily be an uninformative article).

2024-07-17 06:31 UTC, Wilsven approved these changes

2024-07-17 07:38 UTC, Wilsven approved these changes

2024-07-17 07:38 UTC, merged

2024-07-17 13:37 UTC, Wilsven commented
![](https://github.trello.services/images/mini-trello-icon.png) [Review Excel provided by JingYi](https://trello.com/c/w9a1kB4x/146-review-excel-provided-by-jingyi)