Added populate_mongo to populate real data in mongodb
Wilsven/healthhub-content-optimization pull request #64
Opened 2024-07-04 09:21 UTC by sixiannn

- Added input files in data folder for populating mongodb
    - merged_data.parquet
    - edges and cluster pkl exported from cluster_evaluation.ipynb

- Added ./scripts/populate_mongo using input files from data folder

2024-07-04 10:04 UTC, issacj-17 commented
@sixiannn, please run the make lint in the root directory before making a pull request. They will help review any linting and formatting issues with your code. The checks have failed. Also, please assign a reviewer to approve the pull request. Thanks!

2024-07-04 10:07 UTC, Wilsven commented
It would seem the files `db_populator.py` and `cluster_evaluation.ipynb` are not linted. Might want to check and consult the relevant owners. I believe @jwyting worked on `cluster_evaluation.ipynb`.

2024-07-04 10:09 UTC, Wilsven commented
Please consult the `README.md` under the section `Pushing to GitHub` to ensure you have completed the relevant checks before pushing or you will have a lot of failed PRs.

2024-07-04 10:28 UTC, TsienJin commented
Should the data committed? Since its a public repo

@Wilsven

2024-07-04 10:30 UTC, Wilsven commented
> Should the data committed? Since its a public repo
> 
> @Wilsven

Nope, it definitely should not. Good catch, @TsienJin. Giving you this to review and approve since you're owning the frontend and backend portion. Do work with @sixiannn on this to remedy before making another PR. Thanks all!

2024-07-04 10:32 UTC, Wilsven commented
> > Should the data committed? Since its a public repo
> > @Wilsven
> 
> Nope, it definitely should not. Good catch, @TsienJin. Giving you this to review and approve since you're owning the frontend and backend portion. Do work with @sixiannn on this to remedy before making another PR. Thanks all!

Minimally, anyone making a pull from `main` should be able to run whatever script to get the same data needed to populate the database. No need to commit the data to version control. We are versioning control our code for collaboration. Not for data sharing although one might argue there's a use case for this (but for here).

2024-07-04 10:37 UTC, Wilsven commented
@sixiannn One more thing regarding your `ipynb` notebooks. Please refer to #58 under discussion for more information before committing these files into the Kedro pipeline. Do clarify if you have queries. Thanks!

2024-07-04 10:39 UTC, Wilsven commented
> @sixiannn One more thing regarding your `ipynb` notebooks. Please refer to #58 under discussion for more information before committing these files into the Kedro pipeline. Do clarify if you have queries. Thanks!

I have tagged you in that PR (#58) 3 days ago, so you should viewed it.

2024-07-04 10:40 UTC, Wilsven requested changes
@sixiannn Refer to Conversation in #64 and fix issues please.

2024-07-04 16:07 UTC, Wilsven approved these changes

2024-07-05 01:30 UTC, TsienJin requested changes
Hey @sixiannn I've added some comments, please lmk if u have any questions or other comments. Thanks!

2024-07-05 01:30 UTC, TsienJin commented on backend/app/app/scripts/populate_mongo/beanie_documents.py
Hey sorry, since this script is under the same poetry project as the backend, can we reference the documents in this file instead? This way we maintain the schemas more easily and remove duplicated code.

https://github.com/Wilsven/healthhub-content-optimization/blob/webapp/backend/app/app/utils/db_connector/mongo_connector/beanie_documents.py

2024-07-05 01:30 UTC, TsienJin commented on backend/app/app/scripts/populate_mongo/db_populator.py
I would suggest using the `create` methods from `MongoConnector` since its being passed into `DBPopulator`, but this way works too.

https://github.com/Wilsven/healthhub-content-optimization/blob/webapp/backend/app/app/utils/db_connector/mongo_connector/mongo_connector.py

Edit: Can keep it this way, should be ok

2024-07-05 01:30 UTC, TsienJin commented on backend/app/pyproject.toml
> -bson = "^0.5.10"
We need `bson` as a dep in `MongoConnector`, I don't think this should be removed.

2024-07-05 06:13 UTC, sixiannn commented on backend/app/pyproject.toml
> -bson = "^0.5.10"
I faced some compatibility issues for bson and pymongo so had to uninstall bson and reinstall only pymongo. 

In the pymongo documentation, they had a warning message to not install bson package as pymongo comes with its own bson package. 
https://pymongo.readthedocs.io/en/stable/installation.html

Should it still be included?

2024-07-05 06:29 UTC, sixiannn commented on backend/app/app/scripts/populate_mongo/beanie_documents.py
In this script, the ArticleDocument does not have an id field and the id field will be populated by mongodb as an ObjectId. We could reference to the documents in mongo_connector/beanie_documents.py instead if the ArticleDocument can be standardized. 

Would changing to the field id: Optional[PydanticObjectId] = Field(None, alias="_id") be a viable solution? Alternatively, I can assign string id to the articles before populating to mongodb if this is better. Thank you!

2024-07-05 09:08 UTC, TsienJin commented on backend/app/pyproject.toml
> -bson = "^0.5.10"
Lol interesting, cause I had issues with the built in BSON methods from the pymongo library.

Ok lets remove it first.

2024-07-07 05:25 UTC, TsienJin requested changes

2024-07-07 05:25 UTC, TsienJin commented on backend/app/app/scripts/populate_mongo/beanie_documents.py
> +    edges: List[Link[EdgeDocument]] = Field(default=[])
Do you think we can have `edges` as an array of `EdgeDocument`s instead of an array of references?

I get that this is the "proper" way to store these records, but I think that it will result in higher endpoint latency as we have to make more DB queries when constructing the `Edge` pydantic model.

2024-07-07 05:25 UTC, TsienJin commented on backend/app/app/scripts/populate_mongo/beanie_documents.py
Ok, lets stick to ObjectId, will make the necessary changes to `MongoConnector`.

2024-07-07 05:27 UTC, TsienJin commented
Please add docs on how to run the script
- What scripts to run to produce the data files
- Where to place the raw data files
- etc.

Thanks

2024-07-07 12:57 UTC, Wilsven approved these changes

2024-07-08 04:24 UTC, sixiannn commented on backend/app/app/scripts/populate_mongo/beanie_documents.py
> +    edges: List[Link[EdgeDocument]] = Field(default=[])
Have updated to use mongo_connector/beanie_documents.py

2024-07-08 05:21 UTC, TsienJin approved these changes

2024-07-08 05:22 UTC, merged